# Generated by Django 2.0.6 on 2018-09-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ci',
            field=models.CharField(default=1, max_length=21, unique=True),
            preserve_default=False,
        ),
    ]
