# Generated by Django 2.0.6 on 2018-09-11 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_ci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ci',
            field=models.CharField(blank=True, default=None, max_length=21, null=True, unique=True),
        ),
    ]
