version: '3'

services:

    app:
        restart: always
        build:
            context: .
            dockerfile: ./compose/prod/app/Dockerfile
        command: /start.sh
        env_file: .env
        volumes:
            - ./static/:/public/static/
            - ./media/:/public/media/
        expose:
            - "5000"
        depends_on:
            - design-db

    design-db:
        restart: always
        build:
            context: .
            dockerfile: ./compose/prod/db/Dockerfile
        env_file: .env
        volumes:
            - postgis:/var/lib/postgresql/data

    nginx:
        restart: always
        build:
            context: .
            dockerfile: ./compose/prod/nginx/Dockerfile
        volumes:
            - ./media:/public/media:ro
            - ./static:/public/static:ro
            - /var/www:/var/www:ro
        ports:
            - "80:80"
        depends_on:
            - app

volumes:
    postgis:

