# Generated by Django 2.0.6 on 2018-09-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sizes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
