# Generated by Django 2.0.6 on 2018-07-28 02:41

from django.db import migrations
import v1.utils.models.upper_field


class Migration(migrations.Migration):

    dependencies = [
        ('sizes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='name',
            field=v1.utils.models.upper_field.UpperCharField(max_length=255, unique=True),
        ),
    ]
