# Generated by Django 2.0.6 on 2018-07-30 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0002_auto_20180730_1914'),
        ('sizes', '0002_auto_20180727_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='updated')),
                ('product_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sizes', to='colors.ProductColor')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sizes', to='sizes.Size')),
            ],
            options={
                'ordering': ['-id'],
                'get_latest_by': 'created',
            },
        ),
        migrations.AlterUniqueTogether(
            name='productsize',
            unique_together={('size', 'product_color')},
        ),
    ]
