# Generated by Django 2.0.6 on 2018-09-09 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='updated')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='designs.CategoryDesign')),
            ],
            options={
                'ordering': ['-id'],
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='updated')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('img', models.TextField(max_length=5000)),
                ('is_custom', models.BooleanField(default=False)),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('category_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='designs.CategoryDesign')),
            ],
            options={
                'ordering': ['-id'],
                'get_latest_by': 'created',
            },
        ),
    ]
