# Generated by Django 2.0.6 on 2018-10-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='design',
            name='width',
            field=models.FloatField(default=0),
        ),
    ]
