# Generated by Django 2.0.6 on 2018-08-18 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='updated')),
                ('country', models.CharField(default='Chile', max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('commune', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=255)),
                ('secondary_address', models.CharField(blank=True, max_length=255, null=True)),
                ('commentary', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'get_latest_by': 'created',
            },
        ),
    ]
