# Generated by Django 2.0.6 on 2018-08-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Static',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='updated')),
                ('stamped_light', models.IntegerField()),
                ('print_dimension', models.IntegerField()),
                ('paper_dimension', models.IntegerField()),
            ],
            options={
                'ordering': ['-id'],
                'get_latest_by': 'created',
            },
        ),
    ]
