# Generated by Django 2.0.6 on 2018-09-09 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='updated')),
            ],
            options={
                'ordering': ['-id'],
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='PrintType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='updated')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('price', models.IntegerField()),
            ],
            options={
                'ordering': ['-id'],
                'get_latest_by': 'created',
            },
        ),
        migrations.AddField(
            model_name='printproduct',
            name='print_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_products', to='prints.PrintType'),
        ),
        migrations.AddField(
            model_name='printproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_products', to='products.Product'),
        ),
        migrations.AlterUniqueTogether(
            name='printproduct',
            unique_together={('print_type', 'product')},
        ),
    ]
