# Generated by Django 2.0.6 on 2018-08-25 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_producttype'),
        ('prints', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Print',
            new_name='PrintType',
        ),
        migrations.RenameField(
            model_name='printproduct',
            old_name='print',
            new_name='print_type',
        ),
        migrations.AlterUniqueTogether(
            name='printproduct',
            unique_together={('print_type', 'product_type')},
        ),
    ]
