# Generated by Django 2.0.6 on 2018-09-09 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='updated')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('img', models.TextField(max_length=5000)),
            ],
            options={
                'ordering': ['-id'],
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='updated')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_colors', to='colors.Color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_colors', to='products.Product')),
            ],
            options={
                'ordering': ['-id'],
                'get_latest_by': 'created',
            },
        ),
        migrations.AlterUniqueTogether(
            name='productcolor',
            unique_together={('color', 'product')},
        ),
    ]
