# Generated by Django 2.0.6 on 2018-07-29 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='updated')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_products', to='categories.Category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_products', to='products.Product')),
            ],
            options={
                'ordering': ['-id'],
                'get_latest_by': 'created',
            },
        ),
        migrations.AlterUniqueTogether(
            name='categoryproduct',
            unique_together={('category', 'product')},
        ),
    ]
