# Generated by Django 2.0.6 on 2018-07-29 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180728_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='updated')),
                ('name', models.CharField(max_length=255)),
                ('html_content', models.TextField(max_length=10000)),
                ('price', models.IntegerField()),
                ('slug', models.SlugField(unique=True)),
                ('category_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_types', to='products.CategoryProduct')),
            ],
            options={
                'ordering': ['-id'],
                'get_latest_by': 'created',
            },
        ),
    ]
