# Generated by Django 2.0.6 on 2018-10-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180910_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
